import random

fortunes = ['🌟 Your unwavering determination will light the path to opportunities you never imagined possible, so keep moving forward with courage and grace.',
'🍀 An unexpected encounter will soon bring you laughter, wisdom, and a new perspective on life’s intricate tapestry.',
'🌈 The dreams you nurture quietly in your heart are about to blossom into realities that will surprise and delight you beyond measure.',
'🦋 Embrace the changes that come your way, for they will lead you to a place of greater happiness and fulfillment than you ever thought possible.',
'🌞 A moment of kindness extended to a stranger will return to you tenfold, bringing joy and warmth into your life when you least expect it.',
'🌻 Your patience and perseverance in the face of adversity will soon be rewarded with a breakthrough that transforms your journey.',
'🌱 The seeds of effort you plant today will yield a harvest of success and contentment in the seasons to come.',
'🦉 Wisdom gained from past experiences will guide you through the challenges ahead, helping you make choices that shape a brighter future.',
'🌺 A creative spark within you is ready to ignite, leading to a project or idea that brings recognition and satisfaction.',
'🍎 A healthy mind and body will empower you to pursue your goals with renewed energy and confidence, so invest in your well-being.',
'🎉 A celebration is on the horizon, marking a milestone that signifies your growth, resilience, and ability to overcome obstacles.',
'🚀 Taking a bold step outside your comfort zone will open doors to adventures and friendships that enrich your life in unexpected ways.',
'💫 The universe is conspiring in your favor, aligning circumstances so that your efforts will soon yield remarkable results.',
'🌙 Quiet reflection will reveal answers to questions that have lingered in your mind, bringing peace and clarity to your thoughts.',
'🪁 The winds of change are blowing in your direction, carrying with them exciting opportunities for personal and professional growth.',
'🌊 Like the tides, your fortunes are about to turn, bringing a wave of good luck and prosperity into your life.',
'🦄 A unique talent you possess will soon be recognized by others, leading to new avenues for self-expression and achievement.',
'🍁 As the seasons change, so too will your circumstances, bringing fresh beginnings and renewed hope into your world.',
'🔥 Your passion and enthusiasm will inspire those around you, creating a ripple effect of positivity and motivation.',
'🌏 A journey—whether near or far—will introduce you to new cultures, ideas, and friendships that broaden your horizons.',
'🎨 Your artistic side will find a new outlet, allowing you to create something beautiful that touches the hearts of many.',
'🎶 The melody of your life is about to change key, bringing harmony and joy to areas that once felt discordant.',
'🧭 Trust your inner compass, for it will guide you toward choices that align with your deepest values and aspirations.',
'💡 An innovative solution to a lingering problem will soon present itself, bringing relief and satisfaction.',
'🏆 Your hard work and dedication will be acknowledged by someone you respect, boosting your confidence and self-esteem.',
'🌳 The roots you have planted in your relationships will grow stronger, providing support and comfort during challenging times.',
'🛤️ The road ahead may twist and turn, but each step you take brings you closer to the success you seek.',
'🌬️ A breath of fresh air will clear away old doubts, making room for optimism and new beginnings.',
'🕊️ Peace and serenity will fill your days as you let go of past regrets and embrace the present moment.',
'💖 Love and friendship will blossom in unexpected places, enriching your life with warmth and connection.',
'🪙 A financial opportunity is on the horizon, promising growth and stability if you approach it with wisdom and care.',
'🔮 Trust in the mysterious forces at play, for they are guiding you toward a future filled with promise and hope.',
'🧩 The pieces of your life’s puzzle are falling into place, revealing a picture more beautiful than you ever imagined.',
'🛡️ Your strength and resilience will protect you from negativity, allowing you to focus on what truly matters.',
'🌄 A new dawn is breaking, bringing with it the promise of fresh starts and renewed energy.',
'🦅 Your ability to rise above challenges will inspire others to reach for their own dreams.',
'💎 A hidden gem in your life will soon be revealed, bringing joy and excitement to your daily routine.',
'🍃 Simplicity and mindfulness will bring you peace, helping you appreciate the beauty in everyday moments.',
'📚 Knowledge gained from recent experiences will serve you well in an upcoming decision.',
'🎁 A surprise gift—material or emotional—will remind you of the abundance and generosity in your world.',
'🌠 A wish you made long ago is about to come true, bringing happiness and fulfillment into your life.',
'🧘‍♂️ Balance and harmony will be restored as you prioritize self-care and inner peace.',
'🛎️ A long-awaited message will arrive, bringing clarity and direction to your current situation.',
'🍂 Letting go of what no longer serves you will create space for new opportunities and growth.',
'🏡 A sense of belonging and comfort will fill your heart as you strengthen bonds with loved ones.',
'🧵 The threads of your destiny are being woven into a tapestry of success and happiness.',
'🦋 Transformation is underway, and soon you will emerge stronger, wiser, and more confident.',
'🌻 Optimism and gratitude will attract positive energy, making your days brighter and more fulfilling.',
'🕰️ Patience will be rewarded as the timing of your plans aligns perfectly with your desires.',
'🎯 Focus and determination will help you hit your targets, bringing satisfaction and achievement.',
'🛶 Navigating through life’s currents will become easier as you trust your instincts and stay true to yourself.',
'🌟 Your unique perspective is a gift to the world, and sharing it will bring you recognition and respect.',
'🧚‍♀️ Magic is in the air, and delightful surprises await you around every corner.',
'🌿 A period of healing and renewal is beginning, allowing you to move forward with confidence.',
'🦜 Communication will open new doors, so speak your truth with kindness and clarity.',
'🍓 Sweet moments of joy are coming your way, brightening your days and lifting your spirits.',
'🌺 The beauty you bring into the world will be reflected back to you in unexpected ways.',
'🧭 Your journey is guided by purpose and intention, leading you toward meaningful achievements.',
'🧲 Positive energy will attract helpful people and resources into your life.',
'🦉 Trust in your wisdom, for it will illuminate the path ahead and help you make wise choices.',
'🌙 Nighttime reflection will bring insights that guide your actions during the day.',
'🪴 Growth may be slow, but it is steady and sure, leading you toward lasting success.',
'🧗‍♂️ Challenges faced with courage will become stepping stones to greater heights.',
'🌞 The light you shine will brighten the lives of those around you, creating a circle of positivity.',
'🎈 A playful spirit will help you navigate serious matters with grace and ease.',
'🍀 Luck is on your side, so take a chance on something you’ve been considering.',
'🦢 Grace and elegance in your actions will earn you admiration and respect.',
'🌄 The horizon holds new adventures, so set your sights high and embrace what comes.',
'🧸 Comfort and support from friends will help you weather any storm.',
'🍉 Simple pleasures will bring you the greatest joy, so savor each moment.',
'🌊 Ride the waves of change with confidence, knowing you are capable of handling whatever comes your way.',
'🦚 Your unique beauty and talents will be noticed and appreciated by others.',
'🌵 Resilience in tough times will help you flourish when conditions improve.',
'🎤 Your voice matters, so speak up and share your ideas with the world.',
'🧙‍♂️ Wisdom from unexpected sources will help you solve a problem that has been troubling you.',
'🌈 After the rain, a rainbow of possibilities will appear, bringing hope and inspiration.',
'🍒 Good fortune is ripening, ready to be picked and enjoyed.',
'🦦 Playfulness and curiosity will lead you to delightful discoveries.',
'🌙 The night will bring peaceful dreams and restful sleep, preparing you for tomorrow’s adventures.',
'🦩 Stand tall and proud, for your uniqueness is your greatest strength.',
'🌠 A shooting star will grant you a wish, so dream big and believe in magic.',
'🧶 The fabric of your life is rich and colorful, woven with love and experience.',
'🍊 Fresh opportunities are on the horizon, bringing zest and excitement to your days.',
'🦄 Believe in the impossible, for miracles can happen when you least expect them.',
'🌻 Sunflowers turn toward the light, and so will your fortunes as you stay positive.',
'🦒 Reach for new heights, and you will discover talents you never knew you had.',
'🍋 When life gives you lemons, your creativity will turn them into something sweet.',
'🦔 Small acts of kindness will have a big impact on those around you.',
'🌳 Deep roots and strong branches will help you weather any storm.',
'🧁 Life’s sweetness is found in the moments you share with others.',
'🍇 Abundance is coming your way, so be ready to receive it with gratitude.',
'🦜 Colorful experiences will brighten your days and expand your horizons.',
'🌅 Each sunrise brings a new chance to pursue your dreams.',
'🦋 Transformation is a natural part of growth, so embrace the changes ahead.',
'🍄 Unexpected surprises will add magic to your journey.',
'🦦 Your playful nature will attract joyful experiences into your life.',
'🌺 The beauty you create will inspire those around you.',
'🧚‍♂️ Believe in your dreams, for they are closer to coming true than you think.',
'🍍 Stand tall, wear a crown, and stay sweet on the inside.',
'🦚 Your vibrant spirit will attract positive people and opportunities.',
'🌻 Let your light shine, and you will brighten the world.',
'🦩 Embrace your uniqueness, for it is your greatest asset.',
'🍓 Sweet success is within reach, so keep striving for your goals.',
'🦒 Your perspective brings clarity and insight to those around you.',
'🌼 New beginnings are on the horizon, bringing hope and excitement.',
'🐚 Listen to the whispers of your heart, for they will guide you to happiness.',
'🍑 A juicy opportunity is coming your way, so be ready to seize it.',
'🦢 Graceful actions will lead to beautiful outcomes.',
'🌷 The world is blooming with possibilities just for you.',
'🦔 Protect your dreams, and they will flourish.',
'🍉 Refreshing changes are coming, bringing new energy and joy.',
'🦦 Let curiosity lead you to wonderful discoveries.',
'🌸 Every day is a chance to grow and blossom.',
'🦚 Your colorful personality will brighten any room you enter.',
'🍒 Good things are coming, so keep your heart open.',
'🦩 Stand out and be proud of who you are.',
'🌻 Let positivity guide your journey and success will follow.',
'🦒 Reach for the stars and you will achieve greatness.',
'🍍 Sweet moments are ahead, so savor every one.',
'🦔 Small steps will lead to big achievements.',
'🌷 New adventures await, so be ready to explore.',
'🦚 Your kindness will return to you in unexpected ways.',
'🍓 Celebrate your victories, no matter how small.',
'🦩 Shine brightly and inspire those around you.',
'🌸 The future is blooming with promise and hope.',
'🦒 Stand tall and pursue your dreams fearlessly.',
'🍉 Joyful surprises are just around the corner.',
'🦔 Your gentle spirit brings peace to those you love.',
'🌻 Let gratitude fill your heart and happiness will follow.',
'🦚 Embrace new experiences with an open mind.',
'🍒 Sweet rewards await your hard work.',
'🦩 Be bold and let your true colors show.',
'🌷 Growth comes from embracing change.',
'🦒 Your vision will lead you to success.',
'🍍 Stay sweet and positive, no matter what.',
'🦔 Protect your peace and cherish your joys.',
'🌸 Every challenge is an opportunity to bloom.',
'🦚 Your creativity will open new doors.',
'🍓 Savor the sweetness in every moment.',
'🦩 Stand out and make a difference.',
'🌻 Let your optimism light the way.',
'🦒 Reach new heights with courage and hope.',
'🍉 Refresh your spirit with laughter and love.',
'🦔 Small joys will bring you great happiness.',
'🌷 New friendships will enrich your life.',
'🦚 Your energy will attract wonderful things.',
'🍒 Celebrate the beauty of your journey.',
'🦩 Shine with confidence and grace.',
'🌸 The world is ready for your brilliance.',
'🦒 Stand tall and embrace your destiny.',
'🍍 Sweet opportunities are coming your way.',
'🦔 Let kindness be your guiding star.',
'🌻 Your positive outlook will shape your future.',
'🦚 Embrace every moment as a gift.',
'🍓 Joy and abundance are on the horizon.',
'🦩 Let your spirit soar to new heights.',
'🌷 Growth and happiness are within your reach.',
'🦒 Your dreams are worth pursuing.',
'🍉 Refresh your goals and keep moving forward.',
'🦔 Small acts of love will create big changes.',
'🌸 Every day brings new possibilities.',
'🦚 Your light will guide you to success.',
'🍒 Celebrate your unique journey.',
'🦩 Shine brightly and inspire others.',
'🌻 Let hope be your constant companion.',
'🦒 Reach for your dreams with confidence.',
'🍍 Sweet moments are waiting to be discovered.',
'🦔 Protect your happiness and share your joy.',
'🌷 New beginnings are just ahead.',
'🦚 Embrace change with an open heart.',
'🍓 Savor the journey and enjoy the ride.',
'🦩 Stand out and make your mark.',
'🌸 The future is bright and full of promise.',
'🦒 Stand tall and believe in yourself.',
'🍉 Refresh your perspective and find new joy.',
'🦔 Small moments will bring big happiness.',
'🌻 Let gratitude guide your actions.',
'🦚 Your kindness will be returned to you.',
'🍒 Celebrate every step forward.',
'🦩 Shine with positivity and hope.',
'🌷 Growth is a journey, not a destination.',
'🦒 Your courage will lead to success.',
'🍍 Stay sweet and true to yourself.',
'🦔 Protect your dreams and pursue them boldly.',
'🌸 Every challenge is a chance to grow.',
'🦚 Your creativity will bring you joy.',
'🍓 Savor the sweetness of life.',
'🦩 Stand out and embrace your uniqueness.',
'🌻 Let optimism be your guide.',
'🦒 Reach for new horizons.',
'🍉 Refresh your soul with laughter.',
'🦔 Small joys make life beautiful.',
'🌷 New adventures are waiting for you.',
'🦚 Your energy will attract positivity.',
'🍒 Celebrate your progress every day.',
'🦩 Shine with confidence and love.',
'🌸 The world awaits your brilliance.',
'🦒 Stand tall and chase your dreams.',
'🍍 Sweet surprises are on their way.',
'🦔 Protect your happiness and share it.',
'🌻 Let hope light your path.',
'🦚 Embrace every new experience.',
'🍓 Joy and abundance are coming soon.',
'🦩 Let your spirit shine brightly.',
'🌷 Growth and happiness are yours to claim.',
'🦒 Your dreams are within reach.',
'🍉 Refresh your heart with gratitude.',
'🦔 Small acts of kindness matter most.']



def fortune():
    random_fortune = random.randint(0,len(fortunes)-1)
    return (fortunes[random_fortune])


user = input('Enter your name: ')
print(f'Hey {user} ! Here is your fortune for today: \n\n' + fortune())

re_try = input('Want to try again? (Y/N): ')

if re_try == 'Y':
    print(f'Hey {user} ! Here is another one for today: \n\n' + fortune())
elif re_try == 'N':
    print (f'Thanks! Have a good day, {user}!')
else:
    print ('Wrong input.\n Bye!')
